### ISSUE TITLE
Merge v2 to main, make main the default

### ISSUE THREAD

**Issue by jryans** [matrix-org/matrix.to#119]
Now the the new version is deployed, we should merge it to master so it's clear which thing is the live version.

**Comment by JorikSchellekens** [comment]
Can we put it on a 'main' branch instead?

**Comment by jryans** [comment]
Sure, that's even better. 😄

**Comment by jryans** [comment]
We should change the default branch to main in the repo settings as part of this as well then.

**Comment by JorikSchellekens** [comment]
Code is now on /main
