### ISSUE TITLE
Focus highlight on input looks janky

### ISSUE THREAD

**Issue by JorikSchellekens** [matrix-org/matrix.to#120]
![image](https://user-images.githubusercontent.com/23084468/93500555-29892900-f90c-11ea-9fb1-d75273d4de6a.png)

@neilisfragile

**Comment by JorikSchellekens** [comment]
The focus highlight shouldn't show up on site load

**Comment by 532910** [comment]
In FF it looks nice.
In Chromium 83.0.4103.116 I see ugly outline on mouse over:
![image](https://user-images.githubusercontent.com/14617699/93806588-0931d500-fc52-11ea-9de6-d5291e5fd8bc.png)

**Comment by JorikSchellekens** [comment]
Unfortunately there's no way to change the outline radius on any platform except firefox. (Thanks for pointing out that it looks nice there @532910). It is however expected behaviour to have it highlighted on page load.

I think our best bet is to change the input design to be square.

**Comment by jryans** [comment]
We could hide the browser default focus outline for that field and instead show our our decoration when focused perhaps?

**Comment by JorikSchellekens** [comment]
Does this not mess with accessibility extensions that overwrite the default?

**Comment by 532910** [comment]
Focused outline is almost no different from unfocused one in ff:

Focused:
![image](https://user-images.githubusercontent.com/14617699/94012987-21b90100-fdb2-11ea-879b-211a63f7abc6.png)

Unfocused:
![image](https://user-images.githubusercontent.com/14617699/94013010-2978a580-fdb2-11ea-918a-2d2b23469fcd.png)

Moreover, focused is a bit bolder and darker than unfocused.

**Comment by niquewoodhouse** [comment]
> I think our best bet is to change the input design to be square.

@JorikSchellekens I think that's going to be too awkward, with the rounded buttons.  The rounded buttons are coming from the styling of [matrix.org](https://matrix.org/) for consistency.  

> We could hide the browser default focus outline for that field and instead show our own decoration when focused perhaps?

That sounds appropriate to me.  Not sure if, as @JorikSchellekens asks it messes with extensions.  Here's an example if it helps testing/validating at all - https://www.framer.com/pricing/ (tap Contact us in the Custom price box to see a form with the first input selected.

 If that's not feasible than I'd rather explore bottom-border inputs than square

**Comment by JorikSchellekens** [comment]
@t3chguy Could I get your input on this?

**Comment by t3chguy** [comment]
Replacing the default accessibility outlines it typically poor for a11y.
Given that the Framer site has 69 Axe issues I would not recommend using it as an example.

As per https://www.a11yproject.com/posts/2013-01-25-never-remove-css-outlines/ using colour alone is not good enough.
Using a polyfill to remove that outline only for mouse users is acceptable.

**Comment by JorikSchellekens** [comment]
We should be able to figure something out based on point 2. of the article linked

> Style the element itself. You can remove the outline as long as you style the focused element differently (using a combination of color, background-color, border or text-decoration: underline for example). When using this approach, avoid using color alone as the only visual means of determining focus, as colorblind people may not be able to distinguish the focus state from the inactive state.

**Comment by resynth1943** [comment]
We could easily use `border` for this! I would be happy to create a patch.

**Comment by t3chguy** [comment]
@resynth1943 as per https://www.a11yproject.com/posts/2013-01-25-never-remove-css-outlines/ - using a coloured border enough is not enough for a11y.

**Comment by resynth1943** [comment]
@t3chguy I don't understand.

> Style the element itself. You can remove the outline as long as you style the focused element differently (using a combination of color, background-color, border or text-decoration: underline for example). When using this approach, avoid using color alone as the only visual means of determining focus, as colorblind people may not be able to distinguish the focus state from the inactive state.

> Remove outlines for mouse users only, if you truly must do so. Start without applying any outline: none rules. If a mouse event is detected apply those rules using JavaScript. Remove the rules again if keyboard interaction is detected. Here are 2 examples of accessible outline removal scripts:

Are we unable to do both of these ...?

**Comment by t3chguy** [comment]
Read 
https://github.com/matrix-org/matrix.to/issues/120#issuecomment-697533923 and
https://github.com/matrix-org/matrix.to/issues/120#issuecomment-697557380

**Comment by resynth1943** [comment]
> We should be able to figure something out based on point 2. of the article linked

>> Style the element itself. You can remove the outline as long as you style the focused element differently (using a combination of color, background-color, border or text-decoration: underline for example). When using this approach, avoid using color alone as the only visual means of determining focus, as colorblind people may not be able to distinguish the focus state from the inactive state.


> Using a polyfill to remove that outline only for mouse users is acceptable.

Was that an interjection or an agreement?

**Comment by resynth1943** [comment]
As suggested, I propose we hide the `outline` when a mouse is detected, and possibly on mobile, to fix #157.

Now then, the bigger question is what to replace the `outline` with! Perhaps we could use a combination of `background-color` and `border`? Would that fare well for accessibility?

Still though, we definitely need to replace `outline`. I'm saddened that it doesn't have a `radius` :-(
