### ISSUE TITLE
Title font does not wrap correctly

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix.to#122]
![image](https://user-images.githubusercontent.com/1342360/93604005-b390ca80-f9bc-11ea-8f9b-b4441fdaeec7.png)

![image](https://user-images.githubusercontent.com/1342360/93604135-e2a73c00-f9bc-11ea-887c-c13b7d9dd7bd.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox Nightly
 - Version: 82.0a1

Possibly related to #121

**Comment by babolivier** [comment]
Also from what I can see in Firefox's devtools it's supposed to use Helvetica Neue, and has no fallback font, so for systems not having this font install (which afaik is every Linux distro) it fall backs to DejaVu Serif, which is probably not the desired style.

**Comment by t3chguy** [comment]
Could be worse, on Windows it falls back to Times New Roman:

![image](https://user-images.githubusercontent.com/2403652/93756328-d1e50900-fbfc-11ea-8e46-89291d6db7a0.png)

**Comment by tulir** [comment]
Duplicate of #112?

**Comment by anoadragon453** [comment]
@tulir yep, thanks.
