### ISSUE TITLE
Replace PTO with matrix-ircd

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix.to#13]

**Comment by richvdh** [comment]
pto.im is offline

**Comment by z3ntu** [comment]
bump pto.im is dead

**Comment by richvdh** [comment]
bump yourself. PR welcome https://github.com/matrix-org/matrix-doc/blob/master/supporting-docs/projects/README.md

**Comment by richvdh** [comment]
oh my mistake, apologies; that README is for a different project.

(PR still welcome to fix it :) )

**Comment by rogersachan** [comment]
This should be closed.
