### ISSUE TITLE
doesn't respect WCAG contrast recommendations

### ISSUE THREAD

**Issue by 532910** [matrix-org/matrix.to#135]
![image](https://user-images.githubusercontent.com/14617699/93807828-ddafea00-fc53-11ea-860c-d4704e13d59f.png)
https://webaim.org/resources/contrastchecker/?fcolor=C3C3C3&bcolor=FFFFFF

![image](https://user-images.githubusercontent.com/14617699/93807810-d688dc00-fc53-11ea-92ca-94527422abfb.png)
https://webaim.org/resources/contrastchecker/?fcolor=E0E0E0&bcolor=FFFFFF

**Comment by MadLittleMods** [comment]
It looks like we use the default placeholder styles nowadays which is [`#757575` on `#ffffff`](https://webaim.org/resources/contrastchecker/?fcolor=757575&bcolor=FFFFFF) in Chrome for example which passes all of the WCAG checks.

![](https://user-images.githubusercontent.com/558581/134743598-ff912231-1f80-450c-99f2-87c2ff1c5a97.png)

And that screen after doesn't look relevant anymore.

![](https://user-images.githubusercontent.com/558581/134743610-be2c5908-2416-4761-a21f-a31abee7497d.png)



![](https://user-images.githubusercontent.com/558581/134743676-c2965d89-5076-4f9b-bb64-f4f30b5a1018.png)
