### ISSUE TITLE
The "make another link" button is plain wrong

### ISSUE THREAD

**Issue by resynth1943** [matrix-org/matrix.to#142]
**Describe the bug**

When you enter a link into matrix.to, and click Enter, you are presented with a screen that shows the generated URL. While I do like this mechanic...

![image](https://user-images.githubusercontent.com/49915996/94018351-6c358000-fda8-11ea-8405-37befc1e7371.png)

...I personally don't agree that a "reload" icon should be used to signal "back". 

**To Reproduce**
1. Go to matrix.to
2. Enter "@resynth1943:privacytools.io" into the bar, and click Enter
3. See the reload icon
4. Eternal doom!

**Expected behavior**

I expected it not to use an icon that doesn't describe *what it does*. Instead, perhaps an arrow pointing *backwards* (it's "back") would be more appropriate here?

**Screenshots**

**Desktop (please complete the following information):**

N / A

**Smartphone (please complete the following information):**

N / A

**Additional context**

N / A

**Comment by ludwigbald** [comment]
I think this issue is solved by the new matrix.to, where I can't reproduce it.

**Comment by resynth1943** [comment]
Not sure if it's solved, but I'm closing it because I don't have the time to think about this. If anyone else wants to solve it, feel free.
