### ISSUE TITLE
?via parameters aren't preserved in "Accept invite" button

### ISSUE THREAD

**Issue by tulir** [matrix-org/matrix.to#147]
None of the accept/copy invite buttons keep the `?via` parameters, which makes the whole thing rather useless (you won't be able to join the room unless your server already knows about it)

e.g. going to https://matrix.to/#/!ekJXCOhsmAWQUMhDgn:riot.ovh?via=riot.ovh&via=matrix.org&via=kaplu.mba, the Element button links to https://app.element.io/#/room/!ekJXCOhsmAWQUMhDgn:riot.ovh

**Comment by JorikSchellekens** [comment]
Yeah, that's a serious one. I'll prioritise this
