### ISSUE TITLE
says Fractal is a command-line client (!)

### ISSUE THREAD

**Issue by quite** [matrix-org/matrix.to#148]
On https://matrix.to/#/#resist-uniform-normality:public.cat I'm seeing:
```
Fractal
Command-line Matrix interface using Weechat
Click the '+' button in the top right
```
It's not just a copy-paste error in the source, from what I can see. But I'm sorry I didn't have time to weed through this unfamiliar soup for me :) (Surprising amount of lines of web-soup (js,css,html-templates) for that page!)

Thank you for your work on Matrix!

**Comment by aaronraimist** [comment]
That was fixed by https://github.com/matrix-org/matrix.to/pull/140, it probably just hasn't been deployed to matrix.to yet
