### ISSUE TITLE
Matrix.to font-family fallback

### ISSUE THREAD

**Issue by jelv** [matrix-org/matrix.to#150]
Current font-family is only Helvetica Neue. That's not available on Windows.

Suggestion is to use the same fallback from matrix.org: 

font-family: "Helvetica Neue",
        "Helvetica",
        Arial,
        -apple-system,
        BlinkMacSystemFont,
        "Segoe UI",
        Roboto,
        sans-serif,
        "Apple Color Emoji",  /* Emojis*/
        "Segoe UI Emoji", /* Emojis*/
        "Segoe UI Symbol"

**Comment by Half-Shot** [comment]
This was fixed by https://github.com/matrix-org/matrix.to/pull/133. It's just pending a redeploy @JorikSchellekens?

**Comment by JorikSchellekens** [comment]
That's exactly right, thanks @Half-Shot. I'm going to keep the issue open until the changes are deployed

**Comment by jryans** [comment]
This was deployed.
