### ISSUE TITLE
Missing Element Desktop client

### ISSUE THREAD

**Issue by danger89** [matrix-org/matrix.to#160]
**Describe the bug**

When I want to accept the invite and continue further in Element Desktop, it just opens the web based Element not the Desktop app. There is no way to select Element Desktop.

**To Reproduce**
Steps to reproduce the behaviour:
1. matrix.to invite link
2. (enable experimental clients)
3. No link to open Element Desktop client?

**Expected behaviour**

The link should trigger the browser to open a locally installed application in this case Element app.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox

**Comment by danger89** [comment]
Take an example of how Telegram does it correctly, eg: https://t.me/lbryofficial

**Comment by fossdd** [comment]
matrix.to also gives a `element://` protocol, e.g.: `element://vector/webapp/#/user/@fossdd:matrix.org`. On a brand-new-installed firefox: it works. Which version to you use?

**Comment by danger89** [comment]
I think the devs solved it..? Because before I always was redirected to the web version...

**Comment by fossdd** [comment]
So does this work on your side and this issue can be closed?

**Comment by danger89** [comment]
Yes, it works on my side! Thanks
