### ISSUE TITLE
Don't hide "get metadata from homeserver" option by default

### ISSUE THREAD

**Issue by bwindels** [matrix-org/matrix.to#164]
If you come to matrix.to for the first time, you only see pretty meaningless information (the room id). You have to dig into the "About <room id>" section to be able to get a preview, only after clicking a button that is not clear what it does: "Use any homeserver" ... to do what exactly? All this while it would seem that getting a room metadata is what 99% of the users would want. I would not be surprised if most users never go to the effort to figure the above out and use matrix.to without metadata. The "Remember my choice" is also disabled by default. Are we required to do that?

Instead, we could have a simple "Get the best experience and allow getting the room information from _home-server-domain_" [yes] [no] on first visit (with that HS?), visible by default?

**Comment by jryans** [comment]
This flow will be revised as part of implementing the new designs for homeserver consent.

**Comment by Evidlo** [comment]
Could I propose moving this dialog onto the "Choose an app to continue page"?  This way has a bit less friction, and joining via Element is only one click away.

![out](https://user-images.githubusercontent.com/5455841/105953632-195f2400-6039-11eb-9e89-6be471115447.png)
