### ISSUE TITLE
matrix.to links banned on Twitter

### ISSUE THREAD

**Issue by nukeador** [matrix-org/matrix.to#177]
Twitter doesn't allow you to post a matrix.to link, informing that it has been identified by them or a partner as potentially harmful.

**Comment by ludwigbald** [comment]
For reference: [Twitter's help page on blocked URLs](https://help.twitter.com/en/safety-and-security/phishing-spam-and-malware-links)

There it mentions we should fill out [this form](https://help.twitter.com/forms/spam) to notify them that they erroneously blocked matrix.to

**Comment by jryans** [comment]
I also noticed this blocked Twitter DMs as well if they link to matrix.to. I submitted the same Twitter help form for my own link.

**Comment by ludwigbald** [comment]
Update: Twitter seem to allow matrix.to links again: https://mobile.twitter.com/LudwigBald/status/1355606354656980997

**Comment by ara4n** [comment]
it's been fixed for real this time, i hope, thanks to escalating to various twitter employees.
