### ISSUE TITLE
invalid matrix.to link recognized as valid but fails on mobile

### ISSUE THREAD

**Issue by Bubu** [matrix-org/matrix.to#179]
**Describe the bug**
https://matrix.to/#cctg:bubu1.eu is recognized as a valid matrix.to link but it's invalid according to the spec. This leads to the link seeming to work on desktop/in the browser but then failing to work on mobile clients.

**To Reproduce**
1. open https://matrix.to/#cctg:bubu1.eu
2. try to open it on mobile
3. ... it won't load

**Expected behavior**
Don't display the #cctg:bubu1.eu room when visiting https://matrix.to/#cctg:bubu1.eu

**Screenshots**

![image](https://user-images.githubusercontent.com/105185/102351097-30c0e100-3fa6-11eb-8650-f0ba13bbb033.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Archlinux
 - Browser [e.g. chrome, safari] FF 84
 - Version [e.g. 22] matrix.to

**Smartphone (please complete the following information):**
 - Android 8.1
 - Browser [e.g. stock browser, safari] FF 83.1
 - Element Android 1.0.11

**Comment by ludwigbald** [comment]
The correct format for the link is

Same behavior for me, on Android 10 with Chrome. When opening the room in the browser, I get a preview. But when opening the link with Element Android, I get nothing.

There are two things that need to happen: matrix.to should recognize this link as wrong (#178 ) (maybe suggest the correct verison), and Element Android should implement an error message for invalid matrix.to links.

**Comment by Bubu** [comment]
>  implement an error message for invalid matrix.to links.

I does I think? --> I got a toast that said "Not a valid matrix.to link"

**Comment by ludwigbald** [comment]
I don't, though. I'll mention it over there too 👍

**Comment by bwindels** [comment]
I think there is a / missing, does https://matrix.to/#/#cctg:bubu1.eu work?

**Comment by Bubu** [comment]
Nice fix! :-) :tada: 

Thanks @DanilaFe and @bwindels!
