### ISSUE TITLE
include room info in html title

### ISSUE THREAD

**Issue by strk** [matrix-org/matrix.to#19]
I dunno if feasible but it would be nice for the html returned by a room link to include at least the room address. Even better if it also contained name/topic/number of users/privacy...

It is for IRC bots reporting info about URLs, currently just mentioning "the matrix" and nothing about the room itself

**Comment by strk** [comment]
I've understood that matrix.to aims at doing everything on the client-side so that no traces are left on the server about what was requested by clients (for privacy, I guess?). If this is confirmed, there's no way to include room info in html title (as bots would not be executing javascript anyway)

**Comment by t3chguy** [comment]
@strk this is confirmed, there is no server component and just a clientside React app
