### ISSUE TITLE
Provide SVG badges for chat links

### ISSUE THREAD

**Issue by strk** [matrix-org/matrix.to#20]
It's popular to use badges to link to chat rooms, so it'd be nice to have one for matrix.to.
I'm not sure if could be an url serving a javascript generating an SVG on the client side (to keep the current privacy protecting mechanism).

**Comment by strk** [comment]
Like this: http://strk.kbt.io/tmp/matrix_badge.svg (manually tweaked from the gitter one)

**Comment by richvdh** [comment]
Partly solved by #21; a more powerful badge is covered by #3.
