### ISSUE TITLE
Provide generic oEmbed or OpenGraph metadata

### ISSUE THREAD

**Issue by not7cd** [matrix-org/matrix.to#207]
**Is your feature request related to a problem? Please describe.**
When linking in discourse, preview can't be generated:

> Sorry, we were unable to generate a preview for this web page, because the following oEmbed / OpenGraph tags could not be found: description, image 

**Describe the solution you'd like**
Provide generic description and matrix logo as image.

**Comment by t3chguy** [comment]
Contests with https://github.com/matrix-org/matrix.to/issues/182

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/matrix-org/matrix.to/issues/180
