### ISSUE TITLE
matrix.to should have a legal disclaimer

### ISSUE THREAD

**Issue by deniseal** [matrix-org/matrix.to#222]

**Comment by deniseal** [comment]
Proposed wording:

Matrix.to is a service provided by the Matrix.org Foundation which allows you to easily create invites to Matrix rooms and accounts, regardless of your Matrix homeserver. The service is provided "as is" without warranty of any kind, either express, implied, statutory or otherwise. The Matrix.org Foundation shall not be responsible or liable for the room and account contents shared via this service.

**Comment by bwindels** [comment]
Would probably put it on a separate page and put a little link on the link row on the bottom

**Comment by bwindels** [comment]
PR has been merged, just need to deploy
