### ISSUE TITLE
Allow specifying & remember custom webapp locations

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix.to#23]
Currently matrix.to only links to https://riot.im/app for Riot and https://matrix.org/beta for Matrix Console. 

I think it should be user configurable and remembered if the user uses https://chat.disroot.org/ or https://m.tchncs.de/ or some other Riot instance than the riot.im/app so they would get linked to the right place even if they weren't logged in at riot.im.

**Comment by MayeulC** [comment]
I would like to see this.
Maybe add a `<details>` element under Riot, with a text entry field for the app url.

The browser should auto-fill this if configured correctly, and the generated URL would take the given riot instance as the base URL.

**Comment by aaronraimist** [comment]
https://github.com/flaki/matrix.to/tree/custom-riot implements this

**Comment by JorikSchellekens** [comment]
We're looking add this to the latest matrix.to

**Comment by JorikSchellekens** [comment]
https://github.com/matrix-org/matrix.to/issues/107

**Comment by hex-m** [comment]
> We're looking add this to the latest matrix.to

`1.2.0` is released. Is this implemented? How can it be used?

**Comment by ara4n** [comment]
Closing in favour of #197, given this refers to the old version of the app.
