### ISSUE TITLE
Element deeplink does not open desktop app on Chrome OS X

### ISSUE THREAD

**Issue by bwindels** [matrix-org/matrix.to#230]
This is for Matthew on macOS.

**Comment by t3chguy** [comment]
I have the same in Chrome, in FF it works fine. Weirdly if I try to open an element:// link without any `#` in Chrome then it works fine, urlencoding makes electron very upset

**Comment by bwindels** [comment]
So is this an Element bug rather @t3chguy ?

**Comment by t3chguy** [comment]
I think it's a chrome bug given its fine from ff and only has issues from chrome but haven't chased it further than that.

**Comment by ara4n** [comment]
it's super frustrating that matrix.to is almost perfect these days... except deeplinking doesn't work to Element Desktop, so newbies get flung into Element Web despite having Desktop installed and it all goes wrong.

@novocaine perhaps we can find someone to fix this from the app team?

**Comment by ara4n** [comment]
or perhaps @MidhunSureshR could take a look?

**Comment by MidhunSureshR** [comment]
> or perhaps @MidhunSureshR could take a look?

I'll take a look 👍

**Comment by Eveeifyeve** [comment]
This issue is occuring to me.
