### ISSUE TITLE
Deeplinks with roomids for unjoined rooms into Element don't work

### ISSUE THREAD

**Issue by deepbluev7** [matrix-org/matrix.to#270]
**Describe the bug**
When following a matrix.to link, that uses a roomid and explicit vias, those vias are not passed on to Element, which makes the room unjoinable. Example: https://matrix.to/#/!xokVIsEhSxfAuiViWt:linuxdelta.com?via=linuxdelta.com&via=matrix.org&via=matrix.recursiv.com

**To Reproduce**
1. Got to https://matrix.to/#/!xokVIsEhSxfAuiViWt:linuxdelta.com?via=linuxdelta.com&via=matrix.org&via=matrix.recursiv.com
2. Hover over the Element button
3. See that the url is element://vector/webapp/#/room%2F!xokVIsEhSxfAuiViWt%3Alinuxdelta.com
4. Clicking this will fail to join

**Expected behavior**
matrix.to passes the vias to Element so that the room can actually be joined by clicking.

**Comment by richvdh** [comment]
dup #235 ?

**Comment by deepbluev7** [comment]
Looks like it. Seems like I used the wrong search terms!
