### ISSUE TITLE
README.md: HTML example: image does not exist

### ISSUE THREAD

**Issue by iam-TJ** [matrix-org/matrix.to#281]
The UR for the image `https://matrix.to/img/matrix-badge.svg` given in the example HTML code for embedding in other sites does not exist.

**Comment by AnTheMaker** [comment]
I also noticed this!
It seems like the badge is still reachable via this link: https://matrix.to/images-nohash/matrix-badge.svg
Just the original link you mentioned stopped working.
It seems like the fix introduced in [this PR](https://github.com/matrix-org/matrix.to/pull/215) last year somehow stopped working recently... 
This line introduced in said PR should _theoretically_ still write the badge image to the correct location... idk why it stopped working
https://github.com/matrix-org/matrix.to/blob/9b6a282e5fff3aea59e8ebc731576aaf8e824438/scripts/build.js#L64
Maybe you can help, @bwindels?

**Comment by t3chguy** [comment]
Temporarily fixed by updating the README, I bet this got broken as part of the migration of how we deploy m.to - raised internally

**Comment by t3chguy** [comment]
This got fixed by tweaking the deployment
