### ISSUE TITLE
using (matrix.to) room links with element-web

### ISSUE THREAD

**Issue by samo296** [matrix-org/matrix.to#330]
maybe i'm overlooking something or doing it wrong, but i constantly struggle with room links.
i'm mainly using matrix on a server that also provides element-web. whenever i get a room link (almost always a room on this server) i get taken to matrix.to, which is a dead end of course, because the element-web of my server isn't on the offered list (unsurprisinlgy).
then i have to deconstruct the room link (if even possible!) and mix&match it into a working url for my server (or find the server by searching for the channel part of the url):
`https://matrix.to/#/#channel:myserver.com` -> `https://myserver.com/#/room/#channel`

this is ridiculous! is there no better way to do this? the last time i got a room link, my approach wasn't even possible (the roomlink was just insane, it looked basically like this `https://matrix.to/#/!LeTtErSaLaDLeTtErSaLaD:myserver.com/$eVenMorElEtTerSaLaDeVenMorElEtTerSaLaDeVenMorElEtTerSaLaD?via=myserver.com&via=matrix.org&via=anotherserver.com` 🤦 are you kidding me).

**Comment by t3chguy** [comment]
https://web-docs.element.dev/Element%20Web/config.html#customisation--branding `permalink_prefix` - this is an Issue tracker, not a support forum.

**Comment by samo296** [comment]
get fucked
