### ISSUE TITLE
Guests can't join room guests are allowed in

### ISSUE THREAD

**Issue by supagu** [matrix-org/matrix.to#42]
I've setup my matrix room to allow guests:
#trains_and_things:matrix.org
 by checking "Anyone who knows the room's link, including guests" in riot.

Now I setup a guest account and it won't let me join the room.

I'm using the matrix plugin from here: https://gitlab.com/vurpo/godot-matrix, it seems riot.im/app has no guest login so I do not know how to test a guest login outside of the code I've been using to determine if its an issue with Matrix or if there was some API changes that have recently broken the above code.

**Comment by aaronraimist** [comment]
This doesn't seem to be related to matrix.to. If Riot doesn't let you in to the room as a guest then that is a Riot bug 
https://github.com/vector-im/riot-web/issues/new

**Comment by danielweck** [comment]
see https://github.com/vector-im/riot-web/issues/9264
