### ISSUE TITLE
Doesn't work without javascript

### ISSUE THREAD

**Issue by xaur** [matrix-org/matrix.to#43]
Example: https://matrix.to/#/!XqBunHwQIXUiqCaoxq:matrix.org/$1530352168595839HHUVP:matrix.org

**Comment by t3chguy** [comment]
Yes this is by intent, its all generated in the client to protect your privacy. There is no server-side generated content and the server doesn't even receive the `!XqBunHwQIXUiqCaoxq:matrix.org/$1530352168595839HHUVP:matrix.org` bit because its after a `#`

**Comment by xaur** [comment]
Thanks for clarification. At least a short info in the <noscript> tag would improve UX imo.

**Comment by xaur** [comment]
Also, the intermediate page somewhat slows down the UX. How do you feel about a parameter to directly go to pre-selected renderer?

**Comment by t3chguy** [comment]
intermediate page?
