### ISSUE TITLE
Copy room name to clipboard button

### ISSUE THREAD

**Issue by MazeChaZer** [matrix-org/matrix.to#56]
I will try to implement this myself.

**Comment by aaronraimist** [comment]
Related #50

**Comment by MazeChaZer** [comment]
@aaronraimist Will consider that

**Comment by JorikSchellekens** [comment]
The new matrix-two has a copy button is that what you intended @MazeChaZer?

**Comment by MazeChaZer** [comment]
Yeah, let's close this issue :)
