### ISSUE TITLE
Telegram is not receiving the messages from Matrix

### ISSUE THREAD

**Issue by skarmiglione** [matrix-org/matrix.to#58]
Hello, as title says the bots are working fine from Telegram to riot but not in the oposite way i mean messages from riot to telegram are not working? something new?

**Comment by turt2live** [comment]
Are you using the bridge hosted by t2bot.io? If so, there's been some server trouble lately which makes the bridge appear to be non-functional: come visit [#help:t2bot.io](https://matrix.to/#/#help:t2bot.io) for updates and a bit more information.

**Comment by turt2live** [comment]
(closing as this issue doesn't really belong on this repo, regardless of service provider)
