### ISSUE TITLE
Matrix-static is broken

### ISSUE THREAD

**Issue by tgr** [matrix-org/matrix.to#60]
E.g. https://matrix.to/#/!QtykxKocfZaZOUrTwp:matrix.org

`view.matrix.org` redirects to `matrix.org`. It does that in a broken way (stripping the leading `/` and ending up with a bogus domain name) but even if that's fixed manually, the redirection does not seem to produce anything useful. It would probably be better to redirect to an error page explaining that this service does not exist anymore.

**Comment by t3chguy** [comment]
The service is temporarily down since the security breach, it just isn't high priority to bring back up at this time.

**Comment by tmladek** [comment]
Could the link be at least in strike-through or greyed out, then? Right now it's confusing, I've tried inviting less tech-savvy people, and I got reports like "the link you sent doesn't work" and "it 404s", because they liked the blue icon better and then thought riot is broken.

**Comment by tim-seoss** [comment]
It's a good way to link to Matrix channels for users which don't (yet) use Matrix.  Whilst I realise you're super-busy, it doesn't give a good impression at the moment...

**Comment by richvdh** [comment]
see also https://github.com/matrix-org/matrix.org/issues/379

**Comment by Half-Shot** [comment]
The service is now up.
