### ISSUE TITLE
Communities with '/' in their address are "invalid"

### ISSUE THREAD

**Issue by Zeklandia** [matrix-org/matrix.to#62]
Related to #17, attempting to link to a community with a `/` in the address (e.g., `+foo/bar:matrix.org`) does not work.
![image](https://user-images.githubusercontent.com/2998257/61188558-d86a0f00-a64e-11e9-8232-0e2349d22b3a.png)

**Comment by JorikSchellekens** [comment]
Still a problem on matrix-two
