### ISSUE TITLE
Room invite page is confusing

### ISSUE THREAD

**Issue by pv** [matrix-org/matrix.to#69]
The page matrix.to shows for room/etc. invite links is a bit confusing:

- It's unclear what the user is supposed to click to join the room.
- There are several link targets close to each other that lead to different places (room/etc join link / app homepage)
- The actual link/information how to join the room is given on the far right, which usually is the place for unimportant stuff.
- There's some prominently shown "scary looking" information that's not important for users (repeat of the contents of the browser url bar, the room invite url which may be long and contain random characters, instructions how to add apps to the list)
- How do I join with Riot mobile or desktop apps?

Because this page is an entry point to first-time users, it might make sense to check that its design is suitable for this.

![screenshot](https://user-images.githubusercontent.com/35046/80310184-f7462600-87c8-11ea-80df-facb9485f3cc.png)

**Comment by JorikSchellekens** [comment]
I don't think this is relevant for the new room invite page eg https://matrix.to/#/#element-dev:matrix.org

![image](https://user-images.githubusercontent.com/23084468/93785804-64e66900-fc26-11ea-87ce-4fdabc860636.png)
