### ISSUE TITLE
Move link parser and formatter into reusable micro library.

### ISSUE THREAD

**Issue by JorikSchellekens** [matrix-org/matrix.to#73]
There will be a few additive modifications to the matrix.to url scheme.

It would be nice to have a reusable implementation of this for riot-web and other js-based clients.

**Comment by JorikSchellekens** [comment]
Will look at how riot-web and neo do it currently.

**Comment by turt2live** [comment]
> additive modifications to the matrix.to url scheme

What sort of modifications? They might need to go into the spec: https://matrix.org/docs/spec/appendices#matrix-to-navigation

**Comment by JorikSchellekens** [comment]
See https://github.com/matrix-org/matrix.to/issues/74

**Comment by JorikSchellekens** [comment]
The parser and formatter are no longer going to be packaged separately.
