### ISSUE TITLE
Account registration always fails

### ISSUE THREAD

**Issue by Wangmmx** [matrix-org/matrix.to#79]
I just want some WND to continue my test, but I can't register in Riot.
![image](https://user-images.githubusercontent.com/22836587/83136717-8755f300-a11a-11ea-936c-109eb4f84bc1.png)
email-address:
wangmmx0725@163.com
I'm sure this is a working and normal mailbox, What kind of email format is available?

**Comment by t3chguy** [comment]
This is completely unrelated to the matrix.to URL Redirecting service project.

Contact your Matrix homeserver admin.

**Comment by Wangmmx** [comment]
> This is completely unrelated to the matrix.to URL Redirecting service project.
> 
> Contact your Matrix homeserver admin.

Who is the Matrix homeserver admin? and how can I contact ?

**Comment by t3chguy** [comment]
Depends on which Matrix server you are using.
Its like saying who is the Email server admin, depends on which email provider you are using.
