### ISSUE TITLE
Code style in matrix-two branch seems to be different than standard

### ISSUE THREAD

**Issue by jryans** [matrix-org/matrix.to#90]
The main thing I've noticed so far is it uses 2 spaces instead of 4 spaces.

Is there a plan to unify the style...?

**Comment by turt2live** [comment]
please use 4 spaces 😭

**Comment by JorikSchellekens** [comment]
Ah, my bad. Just my vim setup.

**Comment by JorikSchellekens** [comment]
There is a plan to break out the eslint into a separate repo, might start on that today

**Comment by JorikSchellekens** [comment]
Huh, well actually it's the eslint configured by creat-react-app. I think we'll need to eject

**Comment by jryans** [comment]
> I think we'll need to eject

There does appear to be `EXTEND_ESLINT` [advanced config](https://create-react-app.dev/docs/advanced-configuration) env var that could be set, but if that's not enough, may want to eject.
